fixed broken link pointing to localhost
font/k8s-example-apps pull request #5
Opened 2017-07-17 18:07 UTC by onyiny-ang

2017-07-17 19:09 UTC, onyiny-ang reviewed
same problem at the end too

2017-07-17 19:42 UTC, font requested changes
Thanks for the fixes!

2017-07-17 19:42 UTC, font commented on pacman-nodejs-app/docs/pacman-nodejs-app-gke-migration.md
> +Follow [these instructions](https://github.com/font/k8s-example-apps/blob/master/pacman-nodejs-app/docs/kubernetes-cluster-gke-federation.md#create-the-kubernetes-clusters)
No need to have the entire link. Just use `Follow [these instructions](kubernetes-cluster-gke-federation.md#create-the-kubernetes-clusters)`

2017-07-17 19:42 UTC, font commented on pacman-nodejs-app/docs/pacman-nodejs-app-gke-migration.md
> +Follow [these instructions](ttps://github.com/font/k8s-example-apps/blob/master/pacman-nodejs-app/docs/kubernetes-cluster-gke-federation.md#delete-kubernetes-clusters)
Same comment as above.

2017-07-20 06:53 UTC, font approved these changes
I went ahead and made the changes.

2017-07-20 06:53 UTC, merged